Repository googleapis/nodejs-bigquery-reservation, pull requests merged in 2020-11, with the labels that each got.

#27 build(node): add KOKORO_BUILD_ARTIFACTS_SUBDIR to env
  .kokoro/trampoline_v2.sh
  synth.metadata
Labels: api: bigqueryreservation, automerge, cla: yes, context: full

#28 fix: do not modify options object, use defaultScopes
  package.json
  src/index.ts
  src/v1/reservation_service_client.ts
  synth.metadata
  system-test/fixtures/sample/src/index.ts
  system-test/install.ts
Labels: api: bigqueryreservation, automerge, cla: yes

#33 fix(browser): check for fetch on window
  protos/protos.json
  src/v1/reservation_service_client.ts
  synth.metadata
Labels: api: bigqueryreservation, cla: yes, context: none

#35 build: stop tracking generated files
  src/v1/reservation_service_client.ts
  synth.metadata
Labels: api: bigqueryreservation, cla: yes, context: none

#36 docs: spelling correction for "targetting"
  README.md
  synth.metadata
Labels: api: bigqueryreservation, automerge, cla: yes, context: full
