Repository googleapis/nodejs-bigquery-reservation, pull requests merged in 2020-09, with the labels that each got.

#13 build: use the latest build and docs config
  .gitattributes
  .kokoro/continuous/node12/lint.cfg
  .kokoro/continuous/node12/samples-test.cfg
  .kokoro/continuous/node12/system-test.cfg
  .kokoro/continuous/node8/common.cfg
  .kokoro/continuous/node8/test.cfg
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/node10/docs.cfg
  .kokoro/presubmit/node10/lint.cfg
  .kokoro/presubmit/node10/test.cfg
  .kokoro/presubmit/node12/samples-test.cfg
  .kokoro/presubmit/node12/system-test.cfg
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
  .kokoro/presubmit/windows/common.cfg
  .kokoro/presubmit/windows/test.cfg
  .kokoro/publish.sh
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  .kokoro/release/publish.cfg
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  README.md
  api-extractor.json
  linkinator.config.json
  protos/google/cloud/bigquery/reservation/v1/reservation.proto
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  src/v1/reservation_service_client.ts
  synth.metadata
Labels: cla: yes

#14 chore: start tracking obsolete files
  synth.metadata
Labels: cla: yes, context: full

#15 build(test): recursively find test files; fail on unsupported dependency versions
  .github/workflows/ci.yaml
  .mocharc.js
  synth.metadata
Labels: automerge, cla: yes, context: full

#16 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: cla: yes
